CREATE TABLE CUSTOMER(
   ID INTEGER,
   Name VARCHAR(50) ,
   GENDER VARCHAR(50) ,
   LANGUAGES VARCHAR(50) ,
   CREATIONDATE DATE,
   PRIMARY KEY(ID)
);

CREATE TABLE EMAILBOUNCES(
   ID INTEGER,
   BOUNCETYPE VARCHAR(50) ,
   BOUNCEDATE DATE,
   CUSTOMERID INTEGER NOT NULL,
   PRIMARY KEY(ID),
   FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(ID)
);

CREATE TABLE PRODUCT(
   ID INTEGER,
   MAINPRODUCTID INTEGER,
   LANGUAGES VARCHAR(50) ,
   NAME VARCHAR(50) ,
   PRICE_EUR NUMERIC(15,2)  ,
   PRIMARY KEY(ID)
);

CREATE TABLE TRANSACTION(
   ID VARCHAR(50) ,
   CREATIONDATE DATE,
   CUSTOMERID INTEGER NOT NULL,
   PRODUCTID INTEGER NOT NULL,
   PRIMARY KEY(ID),
   FOREIGN KEY(CUSTOMERID) REFERENCES CUSTOMER(ID),
   FOREIGN KEY(PRODUCTID) REFERENCES PRODUCT(ID)
);
